module Pipeline
  VERSION: String
  
  interface _Function
    def to_proc: () -> ^(untyped) -> untyped
  end
end
class Object
  def then_pipe: (*Pipeline::_Function prcs) -> untyped
  
  def sys: (String) -> String
  alias ` public_method
end
