name: Test with RSpec
on:
  push:
    branches: [main]
    paths: [lib/**, spec/**]
  pull_request:
    branches: [main]
    paths: [lib/**, spec/**]
jobs:
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2'
        bundler-cache: true
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: Bearer:${{ github.token }}
    
    - name: Test with RSpec
      run: bundle exec rspec
